#!/bin/sh

cd ./prjlinux

echo "================ compiling owslib for linux debug ================"
make -f makefile_debug clean
make -f makefile_debug 1>owslib_linux_compile_debug.txt 2>&1
mv owslib_linux_compile_debug.txt ../../../10-common/version/compileinfo/ -f

echo "================ compiling owslib for linux release ================"
make -f makefile_release clean
make -f makefile_release 1>owslib_linux_compile_release.txt 2>&1
mv owslib_linux_compile_release.txt ../../../10-common/version/compileinfo/ -f


cd ../../
