//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by UmcWebProj.rc
//
#define IDS_UMCWEBPROJ                  1
#define IDD_ABOUTBOX_UMCWEBPROJ         1
#define IDB_UMCWEBPROJ                  1
#define IDC_Btn_Netwk                   1
#define IDS_UMCWEBPROJ_PPG              2
#define IDS_UMCWEBPROJ_PPG_CAPTION      200
#define IDD_PROPPAGE_UMCWEBPROJ         200
#define IDC_BtnCancel                   201
#define IDC_STATIC_MeetingImage         201
#define IDC_BtnAddr                     203
#define IDC_EDIT_UMC_IP                 203
#define IDC_BtnPublicAddr               203
#define IDD_MAINDIALOG                  204
#define IDC_BtnUser                     204
#define IDC_EDIT_USER_NAME              204
#define IDD_DIALOG_LOGIN                205
#define IDC_EDIT_USER_PSWD              205
#define IDC_BtnTemplate                 205
#define IDC_BtnSystem                   206
#define IDC_CHK_LOGIN                   206
#define IDC_BtnMeetingList              207
#define IDC_BtnTvw                      208
#define IDC_BtnLocalAddr                209
#define IDD_DIALOG_MAIN                 212
#define IDR_TOOLBAR_Main                213
#define IDC_BUTTON2                     215
#define IDC_Btn_Network                 215
#define IDC_Btn_CloseMeeting            215
#define IDC_BTN_SELALL                  215
#define IDC_BtnAllSelect                215
#define IDC_BUTTON_ONOROFF              215
#define IDC_BUTTON_WARNING              215
#define IDC_BTN_PASTE                   215
#define IDC_BUTTON_TIMESYNC             215
#define IDC_BUTTON_DELALL               215
#define IDC_BUTTON_VTR_CHECK_ALL        215
#define IDC_BUTTON_VTR_RECORD_SWITCH    215
#define IDC_BUTTON_AddrShowEx           215
#define IDC_Btn_ConfFormat              215
#define IDC_BUTTON_VTR_PLAYBACK_SWITCH  216
#define IDC_BUTTON_VTR_UNCHECK_ALL      216
#define IDC_Btn_ServerSet               217
#define IDC_BUTTON_ShowEx               217
#define IDC_STATIC_IP                   218
#define IDC_EDIT_IP                     219
#define IDC_BtnServer                   220
#define IDC_BUTTON1                     221
#define IDC_BTN_RETURN                  221
#define IDC_Btn_Logo                    221
#define IDC_Btn_Save                    221
#define IDC_EDIT_Sub                    221
#define IDC_Btn_On                      221
#define IDC_Btn_AllSelect               221
#define IDC_Btn_NewTemplate             221
#define IDC_Btn_System                  221
#define IDC_BtnGk                       221
#define IDC_BTN_ABOUT                   221
#define IDC_BUTTON_BACK                 221
#define IDC_BTN_CONFHP1080P60F          221
#define IDC_BUTTON_DEL_SINGLE           221
#define IDC_BUTTON_CONF_TYPE            221
#define IDC_BTN_HP1080P60F              221
#define IDC_STATIC_IPADDR               222
#define IDC_STATIC_DIR                  222
#define IDC_Btn_Cancel                  222
#define IDC_BTN_CONFHP1080P30F          222
#define IDC_BUTTON_VTR_SAVE             222
#define IDC_BUTTON_SHOW_TYPE            222
#define IDC_BUTTON_BACK2ADDR            222
#define IDC_EDIT_IPAddr                 223
#define IDC_EDIT_FIND                   223
#define IDC_BTN_CONFHP720P30F           223
#define IDC_BUTTON_PLAY_CHOOSE          223
#define IDC_BTN_HP1080P30F              223
#define IDC_STATIC_GetWay               224
#define IDC_BTN_NEW_MEETING             224
#define IDC_BtnSave                     224
#define IDC_BTN_CONFBP1080P60F          224
#define IDC_BUTTON_VTR_CANCEL           224
#define IDC_EDIT_GetWay                 225
#define IDC_BTN_NEW_GRP                 225
#define IDC_BtnMeetingTemplate          225
#define IDC_BTN_CONFBP1080P30F          225
#define IDC_BTN_HP720P60F               225
#define IDC_BTN_COPY                    226
#define IDC_BtnPublic                   226
#define IDC_BTN_CONFBP720P30F           226
#define IDC_BTN_CUT                     227
#define IDC_BtnLocal                    227
#define IDC_BTN_SHOWHP720P30F           227
#define IDC_BTN_EDIT                    228
#define IDC_Btn_Close                   228
#define IDC_BTN_SHOWBP1080P60F          228
#define IDC_BTN_BP1080P60F              228
#define IDC_BTN_DELETE                  229
#define IDC_BtnLogo                     229
#define IDC_BUTTON_LOGO                 229
#define IDC_LIST1                       230
#define IDC_LIST_ADDR_GRP               230
#define IDC_LIST_Current                230
#define IDC_LIST_Template               230
#define IDC_LIST_Test                   230
#define IDC_Btn_VTR                     230
#define IDC_EDIT_MEETINGNAME            231
#define IDC_LIST_Order                  231
#define IDC_LIST_ADDR                   231
#define IDC_BTN_SHOWBP720P30F           231
#define IDC_Btn_ADDREDIT                231
#define IDC_EDIT_MEETINGCODE            232
#define IDC_EDIT_GRPNAME                232
#define IDC_LIST_POLLINGMEETINGLISTLEFT 232
#define IDC_BTN_SHOWBPUXGA60F           232
#define IDC_BTN_BP1080P30F              232
#define IDD_DIALOG_PublicAddr           233
#define IDC_Btn_Test                    233
#define IDC_BTN_SHOWBPWXGA30F           233
#define IDD_DIALOG_SYSTEMSET            234
#define IDC_STATIC_SystemSet            234
#define IDC_BTN_SHOWBPSXGA30F           234
#define IDC_BTN_BP720P60F               234
#define IDD_DIALOG_LOCALADDRBOOK        235
#define IDC_BTN_BPUXGAP60F              235
#define IDC_BTN_BPSXGAP30F              236
#define IDC_STATIC_Title                237
#define IDC_BTN_SHOWHP1080P60F          237
#define IDC_BTN_HP720P30F               237
#define IDD_DIALOG_LOCALADDR_MEETINGEDIT 238
#define IDC_BTN_BPWXGAP30F              238
#define IDD_DIALOG_LOCALADDR_GRPEDIT    239
#define IDC_BTN_SHOWBPWXGA5F            239
#define IDC_BTN_SHOWBPSXGA5F            240
#define IDC_BTN_BP720P30F               240
#define IDR_TOOLBAR_System              241
#define IDC_BTN_SHOWBPXGA5F             241
#define IDC_BTN_BPWXGAP5F               242
#define IDD_DIALOG_SIPSERVERSET         243
#define IDC_BTN_BPXGAP5F                243
#define IDC_BTN_BPSXGAP5F               244
#define IDD_DIALOG_UMSNETWORK           245
#define IDD_DIALOG_UMSNETWORKSET        245
#define IDC_BTN_BP4CIFP25F              245
#define IDC_STATIC_Meetinglist          248
#define IDC_STATIC_CurrentMeeting       248
#define IDD_DIALOG_MEETINFO             249
#define IDC_STATIC_Menu                 254
#define IDC_EDIT1                       255
#define IDC_EDIT_Search                 255
#define IDC_EDIT_Ex                     255
#define IDC_EDIT_Name                   255
#define IDC_EDIT_DOT_HOUR               255
#define IDC_EDIT_VTRName                255
#define IDC_EDIT_VTRSET_VTRNAME         255
#define IDC_EDIT_VTR_FILENAME           255
#define IDC_EDIT_VTRNo                  256
#define IDC_EDIT_VTRSET_DISK_SPACE_AVAILABLE 256
#define IDC_EDIT_Search_Play            256
#define IDC_EDIT_VTRIP                  257
#define IDC_EDIT_VTRSET_DISK_SPACE_TOTAL 257
#define IDR_MENU_MeetingList            259
#define IDC_SwitchBtnNMSvr1             260
#define IDC_SwitchBtnNMSvr2             261
#define IDC_EDIT_NMServerIP1            262
#define IDC_EDIT_NMServerIP2            263
#define IDC_STATIC_OrderMeeting         283
#define IDC_STATIC_Current              284
#define IDC_STATIC_Order                285
#define IDC_BTN_INLOCAL                 289
#define IDC_Btn_Title                   292
#define IDC_Btn_TemplateTitle           293
#define IDC_BtnDelete                   295
#define IDC_Btn_TemplateInfo            296
#define IDC_ServerIP                    297
#define IDC_IP                          298
#define IDC_IP_Sub                      299
#define IDC_IP_GetWay                   300
#define IDC_Btn_GroupInfo               301
#define IDC_Btn_MeetingInfo             302
#define IDC_Btn_PollingInfo             303
#define IDC_CURHAND                     304
#define IDC_STATIC_Name                 304
#define IDC_STATIC_Number               305
#define IDC_STATIC_Type                 306
#define IDC_STATIC_Date                 307
#define IDC_STATIC_StartTime            308
#define IDC_Btn_DiscussInfo             309
#define IDC_Btn_SetTitle                310
#define IDC_Btn_UserTitle1              311
#define IDC_Btn_UserTitle2              312
#define IDC_Btn_NewUser                 313
#define IDC_LIST_User                   314
#define IDD_DIALOG_MEETTEMPLATE         315
#define IDC_STATIC_TemplateName         315
#define IDC_STATIC_TName                315
#define IDD_DIALOG_USERMANAGE           316
#define IDC_STATIC_TemplateNumber       316
#define IDC_STATIC_TNumber              316
#define IDD_DIALOG_Set                  317
#define IDC_STATIC_TemplateType         317
#define IDC_STATIC_TType                317
#define IDC_STATIC_TemplateDate         318
#define IDC_STATIC_TDate                318
#define IDC_STATIC_TemplateStartTime    319
#define IDC_STATIC_TStartTime           319
#define IDC_EDIT_UserName               320
#define IDC_STATIC_TConfRate            320
#define IDC_EDIT_Pwd                    321
#define IDC_STATIC_TShowRate            321
#define IDC_STATIC_UName                322
#define IDC_STATIC_TConfRateUnit        322
#define IDC_STATIC_Pwd                  323
#define IDC_STATIC_TShowRateUnit        323
#define IDC_STATIC_PassWord             324
#define IDC_Btn_SystemTime              325
#define IDC_Btn_GK                      326
#define IDC_BtnEdit                     328
#define IDC_EditName                    329
#define IDC_EditNumber                  330
#define IDC_RADIO_Order                 331
#define IDC_EditConfRate                331
#define IDC_RADIO_Current               332
#define IDC_EditShowRate                332
#define IDC_EditGroup3                  332
#define IDC_EditDate                    333
#define IDC_GroupEditName               333
#define IDC_EditGroup4                  333
#define IDC_EditHour                    334
#define IDC_EditMinute                  335
#define IDC_BtnPlusHour                 336
#define IDC_BtnSubHour                  337
#define IDC_BtnPlusMin                  338
#define IDC_BtnSubConfRate              338
#define IDC_BtnSubMin                   339
#define IDC_BtnSubShowRate              339
#define IDC_STATIC_Mh                   340
#define IDC_EditSec                     340
#define IDC_BtnPlusConfRate             340
#define IDC_LIST_MeetingInfo            341
#define IDC_LIST_GROUPMTLISTEDIT        341
#define IDC_BtnPlus                     341
#define IDC_BtnPlusShowRate             341
#define IDC_GK_IPADDRESS                342
#define IDC_PollingEditName             342
#define IDC_BtnMinus                    342
#define IDC_STC_VER                     343
#define IDC_LIST_POLLINGMTLISTEDIT      343
#define IDC_BtnSubPollingTime           343
#define IDC_BTN_RTRN                    344
#define IDC_BTN_ALLADD                  344
#define IDC_BtnPlusPollingTime          345
#define IDC_STC_TITLE                   346
#define IDC_DATETIMEPICKER_SET          352
#define IDC_STATIC_POLLINGSECOND        353
#define IDC_STATIC_HOMEMEETING          354
#define IDD_DIALOG_SYSTIMESET           355
#define IDC_STATIC_INTERVEL             355
#define IDC_STATIC_BKCHILD              356
#define IDC_STATIC_LOGO                 357
#define IDC_STATIC_RECORDPASSWORD       358
#define IDD_DIALOG1                     359
#define IDD_DIALOG_GKSERVERSET          359
#define IDC_STATIC_TOOLBARBK            359
#define IDC_IPADDR_UMC_IP               360
#define IDC_BUTTON_LOGIN                361
#define IDC_STATIC_COMPANY              362
#define IDC_STATIC_VERSION              363
#define IDC_BUTTON_SAVE                 365
#define IDC_STATIC_GROUPNAME            366
#define IDC_STATIC_MEETNAME             367
#define IDC_STATIC_MEETCODE             368
#define IDC_STATIC_EDITMEET             369
#define IDC_STATIC_EDITGROUP            370
#define IDC_STATIC_IPSUB                371
#define IDC_STATIC_IPGATWAY             372
#define IDC_STATIC_GKONANOFF            373
#define IDR_Save                        374
#define IDC_STATIC_CHILDWNDTITLE        375
#define IDC_STATIC_LEFTTITLE            376
#define IDC_STATIC_RIGHT                377
#define IDC_STATIC_RIGHTTITLE           377
#define IDC_STATIC_DATAFIR              378
#define IDC_STATIC_DATASEC              379
#define IDC_STATIC_DATATHI              380
#define IDC_STATIC_DATAFOR              381
#define IDC_STATIC_DATAFIF              382
#define IDC_BUTTON_CALENDAR             385
#define IDC_EDIT_DATE                   386
#define IDC_BUTTON_CHECKORDERMEET       387
#define IDC_BUTTON_CHECKCURMEET         388
#define IDC_STATIC_MSGCONTENT           389
#define IDC_STATIC_CHILDFRMLEFT         390
#define IDC_STATIC_CHILDFRMRIGHT        391
#define IDC_STATIC_CHILDFRMBOTTOM       391
#define IDC_STATIC_CHILDFRMUP           392
#define IDC_STATIC_CURMEETTITLE         393
#define IDC_STATIC_ORDERMEETTITLE       394
#define IDC_BTN_REVOKE                  395
#define IDC_STATIC_DOTHOUR              396
#define IDC_STATIC_DOTMIN               397
#define IDC_BTN_ALLSEL                  399
#define IDC_BTN_EXPORT                  400
#define IDC_BTN_Refresh                 401
#define IDC_BUTTON_CALLCONF             401
#define IDC_BUTTON_MENU                 404
#define IDC_STATIC_CHECK                405
#define IDC_STATIC_ALLMEET              406
#define IDR_PNG_LOGINWND_BK             407
#define IDC_STATIC_CURMEET              407
#define IDR_PNG_LOGINWND_BKCHILD        408
#define IDC_STATIC_ORDERMEET            408
#define IDR_PNG_LOGINWND_BTN_LOGINDIS   409
#define IDC_BUTTON_SETTOP               409
#define IDR_PNG_LOGINWND_BTN_LOGIN      410
#define IDC_BUTTON_MOVEUP               410
#define IDR_PNG_LOGINWND_LOGO           411
#define IDC_BUTTON_MOVEDOWN             411
#define IDC_STATIC_ICON                 411
#define IDR_PNG_LOGINWND_BTN_ON         412
#define IDC_BUTTON_SETBOTTOM            412
#define IDC_STATIC_MSG                  412
#define IDR_PNG_LOGINWND_BTN_ONDIS      413
#define IDC_BUTTON_REMOVEALL            413
#define IDC_EDIT_DOT_MIN                413
#define IDR_PNG_LOGINWND_BTN_ONDOWN     414
#define IDC_EDIT_HOUR_DOT               414
#define IDR_PNG_LOGINWND_BTN_OFF        415
#define IDC_Btn_Manage                  415
#define IDR_PNG_LOGINWND_BTN_OFFDIS     416
#define IDC_BUTTON_DONE                 416
#define IDR_PNG_LOGINWND_BTN_OFFDOWN    417
#define IDC_STATIC_MEDIAINFO            417
#define IDR_PNG_EDITDELETE              418
#define IDC_BUTTON_MEDIAINFO            418
#define IDR_PNG_EDITDELETEDOWN          419
#define IDC_EditAdaptRes                419
#define IDR_PNG_EDITLEFT                420
#define IDC_STATIC_CONFRATE             420
#define IDR_PNG_EDITLEFTDIS             421
#define IDC_STATIC_SHOWRATE             421
#define IDR_PNG_EDITLEFTSEL             422
#define IDR_PNG_EDITMID                 423
#define IDR_PNG_EDITMIDDIS              424
#define IDR_PNG_EDITMIDSEL              425
#define IDR_PNG_EDITRIGHT               426
#define IDR_PNG_EDITRIGHTDIS            427
#define IDR_PNG_EDITRIGHTSEL            428
#define IDR_PNG_MAINWND_BK              429
#define IDD_DIALOG2                     430
#define IDR_PNG_MAINWND_TOOLBARBK       431
#define IDR_PNG_MAINWND_BTN_DEFSET      432
#define IDR_PNG_MAINWND_BTN_DEFSETDOWN  433
#define IDR_PNG_MAINWND_BTN_DEFSETSEL   434
#define IDR_PNG_MAINWND_BTN_HOME        435
#define IDR_PNG_MAINWND_BTN_HOMEDOWN    436
#define IDR_PNG_MAINWND_BTN_HOMESEL     437
#define IDR_PNG_MAINWND_BTN_LOCALADDR   438
#define IDR_PNG_MAINWND_BTN_LOCALADDRDOWN 439
#define IDC_STATIC_CONFADPRES           439
#define IDR_PNG_MAINWND_BTN_LOCALADDRSEL 440
#define IDC_BTN_MEDIARETURN             440
#define IDC_STATIC_ALLADPRES            440
#define IDR_PNG_MAINWND_BTN_LOGOFF      441
#define IDC_STATIC_ALLRESCOUNT          441
#define IDR_PNG_MAINWND_BTN_LOGOFFDOWN  442
#define IDC_STATIC_VTRName              442
#define IDC_STATIC_RESCOUNT             442
#define IDR_PNG_MAINWND_BTN_USERSEL     443
#define IDC_STATIC_VTRNo                443
#define IDR_PNG_MAINWND_BTN_MEETINFO    444
#define IDC_STATIC_VTRIP                444
#define IDC_STATIC_VTRSET_VTRNAME       444
#define IDR_PNG_MAINWND_BTN_MEETINFODOWN 445
#define IDC_STATIC_VTRSET_DISK_SPACE_AVAILABLE 445
#define IDR_PNG_MAINWND_BTN_MEETINFOSEL 446
#define IDC_STATIC_VTRSET_DISK_SPACE_TOTAL 446
#define IDR_PNG_MAINWND_BTN_MEETTMP     447
#define IDR_PNG_MAINWND_BTN_MEETTMPDOWN 448
#define IDC_BUTTON_VTR_DEL              448
#define IDR_PNG_MAINWND_BTN_MEETTMPSEL  449
#define IDC_BUTTON_VTR_EDIT             449
#define IDR_PNG_MAINWND_BTN_PUBLICADDR  450
#define IDC_BUTTON_VTR_FILEBACK         450
#define IDR_PNG_MAINWND_BTN_PUBLICADDRDOWN 451
#define IDC_STATIC_VTR_FILENAME         451
#define IDR_PNG_MAINWND_BTN_PUBLICADDRSEL 452
#define IDC_STATIC_VTR_FILESIZE         452
#define IDR_PNG_MAINWND_BTN_SYSSETSEL   453
#define IDC_STATIC_VTR_FILESIZE_REAL    453
#define IDR_PNG_MAINWND_BTN_SYSSET      454
#define IDC_STATIC_VTR_FILETIME         454
#define IDR_PNG_MAINWND_BTN_SYSSETDOWN  455
#define IDC_STATIC_VTR_FILETIME_REAL    455
#define IDR_PNG_MAINWND_BTN_USERDOWN    456
#define IDC_EDIT_VTR_SEARCH             456
#define IDR_PNG_MAINWND_BTN_USER        457
#define IDC_STATIC_VTR_RECORD_DOUBLE_CURRENT 457
#define IDC_STATIC_VTR_RECORD_FORM      458
#define IDC_BUTTON_HP1080P60fps         459
#define IDR_PNG_BTN_RETURNDOWN          460
#define IDC_BUTTON_HP1080P30fps         460
#define IDR_PNG_BTN_COPY                461
#define IDC_BUTTON_HP720P30fps          461
#define IDR_PNG_BTN_COPYDIS             462
#define IDC_BUTTON_BP1080P60fps         462
#define IDC_BUTTON_CONF_BP1080P60fps    462
#define IDR_PNG_BTN_COPYDOWN            463
#define IDC_BUTTON_BP1080P30fps         463
#define IDC_BUTTON_CONF_BP1080P30fps    463
#define IDR_PNG_BTN_CUT                 464
#define IDC_BUTTON_BP720P30fps          464
#define IDC_BUTTON_CONF_BP720P30fps     464
#define IDR_PNG_BTN_CUTDIS              465
#define IDC_STATIC_VTR_RECORD_TIME      465
#define IDR_PNG_BTN_CUTDOWN             466
#define IDC_STATIC_VTR_RECORD_TIME_REAL 466
#define IDR_PNG_BTN_DELETE              467
#define IDC_BUTTON_VTR_RECORD_STOP      467
#define IDR_PNG_BTN_DELETEDIS           468
#define IDC_BUTTON_VTR_RECORD_FINISH    468
#define IDR_PNG_BTN_DELETEDOWN          469
#define IDC_STATIC_VTR_PALYBACK         469
#define IDR_PNG_BTN_EDIT                470
#define IDC_STATIC_VTR_PALYBACK_NAME    470
#define IDR_PNG_BTN_EDITDIS             471
#define IDC_BUTTON_VTR_PALYBACK_STOP    471
#define IDR_PNG_BTN_EDITDOWN            472
#define IDC_BUTTON_VTR_PALYBACK_FINISH  472
#define IDR_PNG_BTN_RETURN              473
#define IDC_PROGRESS_VTR_PALYBACK       473
#define IDR_PNG_BTN_NEWGROUP            474
#define IDC_STATIC_VTR_PALYBACK_PROGRESSINFO 474
#define IDR_PNG_BTN_NEWGROUPDOWN        475
#define IDC_BUTTON_VTR_PALYBACK_CHOOSE  475
#define IDC_BUTTON_SHOW_HP1080P60fps    475
#define IDC_BTN_SHOW_HP1080P60fps       475
#define IDR_PNG_BTN_NEWMEET             476
#define IDC_BUTTON_SHOW_HP720P30fps     476
#define IDC_BTN_SHOW_HP1080P50fps       476
#define IDR_PNG_BTN_NEWMEETDOWN         477
#define IDC_BUTTON_RECORD_RETURN        477
#define IDR_PNG_EDITSEARCH              478
#define IDC_STATIC_EQP_ID               478
#define IDC_BUTTON_CHILD_BACK           478
#define IDC_STATIC_EQP_ID_REAL          479
#define IDC_BUTTON_SHOW_BP1080P60fps    479
#define IDC_BTN_SHOW_HP1080P30fps       479
#define IDR_PNG_POPWND_BTN_SAVEDOWN     480
#define IDC_STATIC_CONF_TYPE            480
#define IDR_PNG_POPWND_BK_SMALL         481
#define IDC_STATIC_SHOW_TYPE            481
#define IDR_PNG_POPWND_BTN_CANCLE       482
#define IDC_EDIT_CONF_TYPE              482
#define IDR_PNG_POPWND_BTN_CANCLEDOWN   483
#define IDC_EDIT_SHOW_TYPE              483
#define IDR_PNG_POPWND_BTN_SAVE         484
#define IDC_EDIT_PLAY_CHOOSE            484
#define IDR_PNG_USERWND_BTN_NEWUSERDOWN 485
#define IDC_BUTTON_SHOW_BP720P30fps     485
#define IDC_BTN_SHOW_HP1080P25fps       485
#define IDR_PNG_USERWND_BTN_NEWUSER     486
#define IDC_BUTTON_SHOW_BPUXGA60fps     486
#define IDC_BTN_SHOW_HP720P60fps        486
#define IDR_PNG_USERWND_BTN_NEWUSERDIS  487
#define IDC_STATIC_H264                 487
#define IDR_PNG_BTN_ALLSELDOWN          488
#define IDC_BUTTON_SHOW_BPWXGA30fps     488
#define IDC_BTN_SHOW_HP720P50fps        488
#define IDR_PNG_BTN_ALLSEL              489
#define IDC_BUTTON_SHOW_BPSXGA30fps     489
#define IDC_BTN_SHOW_HP720P30fps        489
#define IDR_PNG_BTN_SAVEDOWN            490
#define IDC_BUTTON_SHOW_BPWXGA5fps      490
#define IDC_BTN_SHOW_HP720P25fps        490
#define IDR_PNG_BTN_CANCEL              491
#define IDC_BUTTON_SHOW_BPSXGA5fps      491
#define IDR_PNG_BTN_CANCELDOWN          492
#define IDC_BUTTON_SHOW_BPXGA5fps       492
#define IDC_BTN_SHOW_BP1080P60fps       492
#define IDR_PNG_BTN_SAVE                493
#define IDC_BTN_SHOW_BP1080P50fps       493
#define IDR_PNG_BTN_NEWTMPDOWN          494
#define IDC_BUTTON_VTR_RECORD_START     494
#define IDR_PNG_BTN_NEWTMP              495
#define IDC_BUTTON_VTR_PALYBACK_START   495
#define IDR_PNG_BTN_NEWTMPDIS           496
#define IDC_BUTTON_VTR_RECORD_RESUME    496
#define IDR_PNG_WNDCHILDRIGHT           497
#define IDC_BUTTON_CONF_HP1080P60fps    497
#define IDC_BTN_CONF_HP1080P60fps       497
#define IDR_PNG_WNDCHILDLEFT            498
#define IDC_BUTTON_CONF_HP1080P30fps    498
#define IDC_BTN_CONF_HP1080P50fps       498
#define IDR_PNG_WNDCHILDMID             499
#define IDC_BUTTON_CONF_HP720P30fps     499
#define IDC_BTN_CONF_HP1080P30fps       499
#define IDD_DIALOG_WARNING              500
#define IDC_STATIC_VTRSET_VTRNAME_REAL  500
#define IDC_BUTTON_VTR_PALYBACK_RESUME  500
#define IDR_PNG_WARNINGWND_BK           501
#define IDC_STATIC_VTRSET_DISK_SPACE_AVAILABLE_REAL 501
#define IDC_SPIN1                       501
#define IDC_BTN_CONF_HP1080P25fps       501
#define IDR_PNG_WARNINGWND_BTNACTIVE    502
#define IDC_STATIC_VTRSET_DISK_SPACE_TOTAL_REAL 502
#define IDC_STATIC_EDIT_RECORD_NAME     502
#define IDC_BTN_CONF_HP720P60fps        502
#define IDR_PNG_WARNINGWND_BTN          503
#define IDC_STATIC_RECORD_NAME          503
#define IDC_BTN_CONF_HP720P50fps        503
#define IDR_PNG_LIST_BTCEN              504
#define IDC_EDIT_RECORD_NAME            504
#define IDC_BTN_CONF_HP720P30fps        504
#define IDR_PNG_LIST_BTLEFT             505
#define IDC_BUTTON_AddEntry             505
#define IDC_BTN_CONF_HP720P25fps        505
#define IDR_PNG_LIST_BTRIGHT            506
#define IDC_BUTTON_Refresh              506
#define IDC_BTN_SHOW_BP1080P30fps       506
#define IDR_PNG_LIST_CENLEFT            507
#define IDC_BUTTON_AllSel               507
#define IDC_BTN_SHOW_BP1080P25fps       507
#define IDR_PNG_LIST_CENRIGHT           508
#define IDC_BUTTON_AllNoSel             508
#define IDC_BTN_CONF_BP1080P60fps       508
#define IDR_PNG_LIST_DOWN               509
#define IDC_STATIC_CnName               509
#define IDC_BTN_CONF_BP1080P50fps       509
#define IDR_PNG_LIST_SPLIT              510
#define IDC_EDIT_EntryName              510
#define IDC_BTN_CONF_BP1080P30fps       510
#define IDR_PNG_LIST_TOPCEN             511
#define IDC_STATIC_CnNumber             511
#define IDC_BTN_CONF_BP1080P25fps       511
#define IDR_PNG_LIST_TOPLEFT            512
#define IDC_EDIT_EntryNumber            512
#define IDC_BTN_CONF_BP720P60fps        512
#define IDR_PNG_LIST_TOPRIGHT           513
#define IDC_BUTTON_DeleteItem           513
#define IDC_BTN_CONF_BP720P50fps        513
#define IDR_PNG_LIST_ADD                514
#define IDC_BUTTON_Copy                 514
#define IDC_BTN_CONF_BP720P30fps        514
#define IDR_PNG_LIST_ADDDOWN            515
#define IDC_BUTTON_Cut                  515
#define IDC_BTN_CONF_BP720P25fps        515
#define IDR_PNG_LISTITEM_WIDTHLEFT      516
#define IDC_BUTTON_Paste                516
#define IDC_BTN_CONF_BP4CIF25fps        516
#define IDR_PNG_LIST_CHECKDOWN          517
#define IDC_BUTTON_Revoke               517
#define IDC_BTN_SHOW_BP720P60fps        517
#define IDR_PNG_LIST_CHECKSEL           518
#define IDC_BUTTON_Delete               518
#define IDC_BTN_SHOW_BP720P50fps        518
#define IDR_PNG_LIST_DEL                519
#define IDC_BUTTON_LoadToLocal          519
#define IDC_BTN_SHOW_BP720P30fps        519
#define IDR_PNG_LIST_GROUP              520
#define IDC_BUTTON_CANCEL               520
#define IDC_BTN_SHOW_BP720P25fps        520
#define IDR_PNG_LIST_GROUPSEL           521
#define IDC_BUTTON_EDIT                 521
#define IDC_BTN_SHOW_BP4CIF25fps        521
#define IDR_PNG_LISTITEM_SHORTLEFT      522
#define IDC_BTN_SHOW_BPUXGA60fps        522
#define IDR_PNG_LISTITEM_SHORTLEFTSEL   523
#define IDC_BTN_SHOW_BPWXGA30fps        523
#define IDR_PNG_LISTITEM_SHORTMID       524
#define IDC_BTN_SHOW_BPSXGA30fps        524
#define IDR_PNG_LISTITEM_SHORTMIDSEL    525
#define IDC_EDIT3                       525
#define IDC_BTN_SHOW_BPWXGA5fps         525
#define IDR_PNG_LIST_NOCHECK            526
#define IDC_STATIC_ALL                  526
#define IDC_BTN_SHOW_BPSXGA5fps         526
#define IDR_PNG_LISTITEM_SHORTRIGHT     527
#define IDC_STATIC_GROUP                527
#define IDC_BTN_SHOW_BPXGA5fps          527
#define IDR_PNG_LISTITEM_SHORTRIGHTSEL  528
#define IDC_STATIC_ONLINE               528
#define IDC_STATIC_NOTONLINE            529
#define IDC_STATIC_RECORD               529
#define IDR_PNG_LISTITEM_WIDTHLEFTSEL   530
#define IDC_STATIC_NEW_GROUP            530
#define IDC_STATIC_PLAY                 530
#define IDR_PNG_LISTITEM_WIDTHMID       531
#define IDC_STATIC_IMPORT_ADDRBOOK      531
#define IDC_STATIC_SHOW_TYPE_REAL       531
#define IDR_PNG_LISTITEM_WIDTHMIDSEL    532
#define IDC_STATIC_NEW_GROUP_ICON       532
#define IDC_STATIC_CONF_TYPE_REAL       532
#define IDR_PNG_LISTITEM_WIDTHRIGHT     533
#define IDC_STATIC_IMPORT_ADDRBOOK_ICON 533
#define IDC_STATIC_WAIT_MSG             533
#define IDC_STATIC_WAIT_ICON            534
#define IDC_STATIC_VideoProtocol        535
#define IDR_PNG_LISTITEM_WIDTHRIGHTSEL  536
#define IDR_PNG_MEETTMPWND_BTN_ALLADD   537
#define IDR_PNG_MEETTMPWND_BTN_DOWN     538
#define IDC_STATIC_Res                  538
#define IDR_PNG_MEETTMPWND_BTN_DOWNDOWN 539
#define IDC_BUTTON_1080P                539
#define IDR_PNG_MEETTMPWND_BTN_MEETGROUP 540
#define IDC_BUTTON_720P                 540
#define IDR_PNG_MEETTMPWND_BTN_MEETGROUPDOWN 541
#define IDC_STATIC_FrameRate            541
#define IDR_PNG_MEETTMPWND_BTN_MEETGROUPSEL 542
#define IDC_BUTTON_60fps                542
#define IDR_PNG_MEETTMPWND_BTN_MEETINFO 543
#define IDC_BUTTON_50fps                543
#define IDR_PNG_MEETTMPWND_BTN_MEETINFODOWN 544
#define IDC_BUTTON_30fps                544
#define IDR_PNG_MEETTMPWND_BTN_MEETINFOSEL 545
#define IDC_BUTTON_25fps                545
#define IDR_PNG_MEETTMPWND_BTN_MEETPOLLING 546
#define IDC_STATIC_VideoProtocolShow    546
#define IDR_PNG_MEETTMPWND_BTN_MEETPOLLINGDOWN 547
#define IDC_BUTTON_H264HPShow           547
#define IDR_PNG_MEETTMPWND_BTN_MEETPOLLINGSEL 548
#define IDC_BUTTON_H264BPShow           548
#define IDC_Btn_ShowFormat              548
#define IDR_PNG_MEETTMPWND_BTN_ALLADDDIS 549
#define IDC_STATIC_ResShow              549
#define IDC_BUTTON_MpegAACLD            549
#define IDR_PNG_MEETTMPWND_BTN_ALLADDDOWN 550
#define IDC_BUTTON_1080PShow            550
#define IDC_Btn_AudioFormat             550
#define IDC_STATIC_REC_FILENAME         550
#define IDR_PNG_MEETTMPWND_BTN_ALLREMOVE 551
#define IDC_BUTTON_720PShow             551
#define IDC_STATIC_REC_FILENAME_REAL    551
#define IDR_PNG_MEETTMPWND_BTN_ALLREMOVEDOWN 552
#define IDC_STATIC_FrameRateShow        552
#define IDR_PNG_MEETTMPWND_BTN_ALLSEL   553
#define IDC_BUTTON_UXGAShow             553
#define IDR_PNG_MEETTMPWND_BTN_ALLSELDOWN 554
#define IDC_BUTTON_WXGAShow             554
#define IDR_PNG_MEETTMPWND_BTN_ALLSELCANCEL 555
#define IDC_BUTTON_SXGAShow             555
#define IDR_PNG_MEETTMPWND_BTN_ALLSELCANCELDOWN 556
#define IDC_BUTTON_XGAShow              556
#define IDR_PNG_MEETTMPWND_BTN_DRAG     557
#define IDC_BUTTON_60fpsShow            557
#define IDR_PNG_MEETTMPWND_BTN_UPDOWN   558
#define IDC_BUTTON_50fpsShow            558
#define IDR_PNG_MEETTMPWND_BTN_DRAGCANCELDOWN 559
#define IDC_BUTTON_30fpsShow            559
#define IDR_PNG_MEETTMPWND_BTN_DRAGCANCEL 560
#define IDC_BUTTON_25fpsShow            560
#define IDC_BUTTON_5fpsShow             561
#define IDR_PNG_MEETTMPWND_BTN_SETBOTTOM 562
#define IDC_BUTTON_H264HP               562
#define IDR_PNG_MEETTMPWND_BTN_SETBOTTOMDOWN 563
#define IDC_BUTTON_H264BP               563
#define IDR_PNG_MEETTMPWND_BTN_SETTOP   564
#define IDC_STATIC_DISCUSS              564
#define IDR_PNG_MEETTMPWND_BTN_SETTOPDOWN 565
#define IDC_STATIC_GROUP1               565
#define IDR_PNG_MEETTMPWND_BTN_UP       566
#define IDC_EditGroup1                  566
#define IDR_PNG_BTN_CANCELALLSELDOWN    567
#define IDC_STATIC_GROUP4               567
#define IDR_PNG_BTN_CANCELALLSEL        568
#define IDC_STATIC_GROUP3               568
#define IDR_PNG_INDEX_J                 569
#define IDC_STATIC_TGroup1              569
#define IDC_BUTTON_G711A                569
#define IDR_PNG_INDEX_Q                 570
#define IDC_STATIC_TGroup2              570
#define IDC_BUTTON_G719                 570
#define IDR_PNG_INDEX_BK                571
#define IDC_STATIC_TGroup4              571
#define IDC_BUTTON_G7221                571
#define IDR_PNG_INDEX_A                 572
#define IDC_STATIC_TGroup3              572
#define IDC_BUTTON_G711U                572
#define IDR_PNG_INDEX_B                 573
#define IDC_EditGroup2                  573
#define IDC_BUTTON_MP3                  573
#define IDR_PNG_INDEX_C                 574
#define IDC_STATIC_GROUP2               574
#define IDC_BUTTON_MpegAACLC            574
#define IDR_PNG_INDEX_D                 575
#define IDC_BtnDiscuss                  575
#define IDR_PNG_INDEX_E                 576
#define IDC_BtnSwitchPolling            576
#define IDR_PNG_INDEX_F                 577
#define IDR_PNG_INDEX_G                 578
#define IDR_PNG_INDEX_H                 579
#define IDR_PNG_INDEX_I                 580
#define IDR_PNG_INDEX_W                 581
#define IDR_PNG_INDEX_K                 582
#define IDR_PNG_INDEX_L                 583
#define IDR_PNG_INDEX_M                 584
#define IDR_PNG_INDEX_N                 585
#define IDR_PNG_INDEX_O                 586
#define IDR_PNG_INDEX_P                 587
#define IDR_PNG_INDEX_R                 588
#define IDR_PNG_INDEX_S                 589
#define IDR_PNG_INDEX_T                 590
#define IDR_PNG_INDEX_U                 591
#define IDR_PNG_INDEX_V                 592
#define IDR_PNG_INDEX_X                 593
#define IDR_PNG_INDEX_Y                 594
#define IDR_PNG_INDEX_Z                 595
#define IDR_PNG_RADIO_UNSELDIS          596
#define IDR_PNG_BTN_PLUS                597
#define IDR_PNG_BTN_PLUSDOWN            598
#define IDR_PNG_BTN_SUB                 599
#define IDR_PNG_BTN_SUBDOWN             600
#define IDR_PNG_RADIO_SEL               601
#define IDR_PNG_RADIO_SELDIS            602
#define IDR_PNG_RADIO_UNSEL             603
#define IDR_PNG_CALENDAR_SEL            604
#define IDR_PNG_CALENDAR                605
#define IDR_PNG_CALENDAR_BK             606
#define IDR_PNG_CALENDAR_DOWN           607
#define IDR_PNG_CALENDAR_NEXTMONTH      608
#define IDR_PNG_CALENDAR_NEXTMONTHDOWN  609
#define IDR_PNG_CALENDAR_PREMONTH       610
#define IDR_PNG_CALENDAR_PREMONTHDOWN   611
#define IDD_DIALOG_CALENDAR             612
#define IDR_PNG_MESSAGE_CANCEL          613
#define IDR_PNG_MESSAGE_CANCELDOWN      614
#define IDR_PNG_MESSAGE_OK              615
#define IDR_PNG_MESSAGE_OKDOWN          616
#define IDD_DIALOG_MESSAGEBOX           617
#define IDR_PNG_MEETLISTWND_BTN_CLOSEMEET 620
#define IDR_PNG_MEETLISTWND_BTN_CLOSEMEETDIS 621
#define IDR_PNG_MEETLISTWND_BTN_CLOSEMEETDOWN 622
#define IDR_PNG_MEETLISTWND_BTN_SEPALEFT 623
#define IDR_PNG_MEETLISTWND_BTN_SEPAMID 624
#define IDR_PNG_MEETLISTWND_BTN_SEPARIGHT 625
#define IDR_PNG_BTN_PASTEDOWN           626
#define IDR_PNG_BTN_PASTE               627
#define IDR_PNG_POPWND_BK_BIG           628
#define IDR_PNG_BTN_CANCELALLSELDIS     630
#define IDR_PNG_BTN_ALLSELDIS           631
#define IDD_DIALOG_GLOBALADDRBOOK       632
#define IDR_PNG_BTN_EXPORT              633
#define IDR_PNG_BTN_EXPORTDOWN          634
#define IDR_PNG_BTN_EXPORTDIS           635
#define IDR_PNG_BTN_Refresh             636
#define IDR_PNG_BTN_RefreshDOWN         637
#define IDR_PNG_MEETTMPWND_BTN_CALLCONFDOWN 638
#define IDR_PNG_MEETTMPWND_BTN_CALLCONF 639
#define IDD_DIALOG_MENUBAR              640
#define IDR_PNG_MEETLISTWND_BK          641
#define IDR_PNG_MEETLISTWND_BTN_CHECK   642
#define IDR_PNG_MEETLISTWND_BTN_CHECKMENUDOWN 643
#define IDR_PNG_MEETLISTWND_BTN_CHECKMENU 644
#define IDR_PNG_MEETLISTWND_BTN_CHECKMENUSEL 645
#define IDR_PNG_BTN_TIMESYNCDOWN        646
#define IDR_PNG_BTN_TIMESYNC            647
#define IDR_PNG_BTN_EDITSYSWND_DOWN     648
#define IDR_PNG_BTN_EDITSYSWND          649
#define IDR_PNG_MEETTMPWND_BTN_UPDOWNDIS 650
#define IDR_PNG_MEETTMPWND_BTN_SETBOTTOMDIS 651
#define IDR_PNG_MEETTMPWND_BTN_SETTOPDIS 652
#define IDR_PNG_MEETTMPWND_BTN_UPDIS    653
#define IDD_DIALOG_WAITREFRESH          654
#define IDR_PNG_WAITPIC1                655
#define IDR_PNG_WAITPIC2                656
#define IDR_PNG_WAITPIC3                657
#define IDR_PNG_WAITPIC4                658
#define IDR_PNG_BTN_LOCALADDRCANCEL     659
#define IDR_PNG_MAINWNDEMY_BK           660
#define IDD_DIALOG_TVWMANAGE            661
#define IDR_PNG_TVW                     662
#define IDR_PNG_TVWDOWN                 663
#define IDR_PNG_TVWICON_ONLINE          664
#define IDR_PNG_TVWICON_OFFLINE         665
#define IDR_PNG_LISTSLIDER_BKGTOP       666
#define IDR_PNG_LISTSLIDER_BKGMIDDLE    667
#define IDR_PNG_LISTSLIDER_BKGBOTTOM    668
#define IDR_PNG_LISTSLIDER_DOWNBOTTOM   669
#define IDR_PNG_LISTSLIDER_DOWNMIDDLE   670
#define IDR_PNG_LISTSLIDER_DOWNTOP      671
#define IDR_PNG_LISTSLIDER_NORMALBOTTOM 672
#define IDR_PNG_LISTSLIDER_NORMALMIDDLE 673
#define IDR_PNG_LISTSLIDER_NORMALTOP    674
#define IDR_PNG_HORISLIDER_BKGLEFT      676
#define IDR_PNG_HORISLIDER_BKGMID       677
#define IDR_PNG_HORISLIDER_BKGRIGHT     678
#define IDR_PNG_HORISLIDER_DOWNLEFT     679
#define IDR_PNG_HORISLIDER_DOWNMID      680
#define IDR_PNG_HORISLIDER_DOWNRIGHT    681
#define IDR_PNG_HORISLIDER_NORMALLEFT   682
#define IDR_PNG_HORISLIDER_NORMALMID    683
#define IDR_PNG_HORISLIDER_NORMALRIGHT  684
#define IDR_PNG_MAINWND_BTN_TVWMANAGE   685
#define IDR_PNG_MAINWND_BTN_TVWMANAGEDOWN 686
#define IDR_PNG_MAINWND_BTN_TVWMANAGESEL 687
#define IDR_PNG_TVW_GROUPBKG            688
#define IDR_PNG_BTN_DONE                689
#define IDR_PNG_BTN_DONEDOWN            690
#define IDR_PNG_BTN_REMOVEALL           691
#define IDR_PNG_BTN_REMOVEALLDOWN       692
#define IDR_PNG_BTN_MANAGE              693
#define IDR_PNG_BTN_MANAGEDOWN          694
#define IDR_PNG_BTN_MANAGEDISABLE       695
#define IDR_PNG_LIST_ENTER              696
#define IDR_PNG_LIST_ENTERDOWN          697
#define IDR_PNG_TVW_OFFLINE             698
#define IDR_PNG_TVW_OFFLINEDOWN         699
#define IDR_PNG_BTN_REMOVEALLDISABLE    700
#define IDR_PNG_BTN_EDITMEDIALEFT       701
#define IDR_PNG_BTN_EDITMEDIAMID        702
#define IDR_PNG_BTN_EDITMEDIARIGHT      703
#define IDD_DIALOG_MEDIAICFG            704
#define IDR_PNG_CHECK_SEL               705
#define IDR_PNG_CHECK_SELDIS            706
#define IDR_PNG_CHECK_UNSEL             707
#define IDR_PNG_CHECK_UNSELDIS          708
#define IDD_DIALOG_NMCFG                709
#define IDC_STATIC_NMSvrIP1             710
#define IDC_STATIC_NMServerIP1          711
#define IDC_STATIC_NMReadCommunity1     712
#define IDC_EDIT_NMReadCommunity1       713
#define IDC_STATIC_NMWriteCommunity1    714
#define IDC_EDIT_NMWriteCommunity1      715
#define IDC_STATIC_NMGetSetPort1        716
#define IDC_EDIT_NMGetSetPort1          717
#define IDC_STATIC_NMTrapPort1          718
#define IDC_EDIT_NMTrapPort1            719
#define IDC_STATIC_NMServerIP2          720
#define IDC_STATIC_NMReadCommunity2     721
#define IDC_EDIT_NMReadCommunity2       722
#define IDC_STATIC_NMWriteCommunity2    723
#define IDC_EDIT_NMWriteCommunity2      724
#define IDC_STATIC_NMGetSetPort2        725
#define IDC_EDIT_NMGetSetPort2          726
#define IDC_STATIC_NMTrapPort2          727
#define IDC_EDIT_NMTrapPort2            728
#define IDC_STATIC_NMSvrIP2             729
#define IDR_PNG_WNDCHILDVERTBOTTOM      730
#define IDR_PNG_WNDCHILDVERTTOP         731
#define IDR_PNG_WNDCHILDVERTMID         732
#define IDD_DIALOG_VTRCFG               733
#define IDD_DIALOG_VTRSET               734
#define IDD_DIALOG_VIDEOFILELIST        735
#define IDD_DIALOG_VTR                  736
#define IDR_PNG_MAINWND_BTN_VTRSEL      737
#define IDD_DIALOG_VIDEORECORD          737
#define IDR_PNG_MAINWND_BTN_VTRDOWN     738
#define IDD_DIALOG_VIDEORECORD_EP       738
#define IDR_PNG_MAINWND_BTN_VTR         739
#define IDD_DIALOG_VIDEORECORD_NAME_EDIT 739
#define IDD_DIALOG_ADDREDIT             740
#define IDR_PNG_BTN_START_RECORD_NORMAL 747
#define IDR_PNG_BTN_START_RECORD_DOWN   748
#define IDR_PNG_BTN_START_RECORD_DISABLE 749
#define IDR_PNG_BTN_PAUSE_RECORD_NORMAL 751
#define IDR_PNG_FINISH_RECORD_DISABLE   752
#define IDR_PNG_FINISH_RECORD_DOWN      753
#define IDR_PNG_FINISH_RECORD_NORMAL    754
#define IDR_PNG_PAUSE_RECORD_DISABLE    755
#define IDR_PNG_PAUSE_RECORD_DOWN       756
#define IDR_PNG_BTN_START_PLAY_NORMAL   757
#define IDR_PNG_BTN_FINISH_PLAY_DISABLE 758
#define IDR_PNG_BTN_FINISH_PLAY_DOWN    759
#define IDR_PNG_FINISH_PLAY_NORMAL      760
#define IDR_PNG_BTN_PAUSE_PLAY_DISABLE  761
#define IDR_PNG_BTN_PAUSE_PLAY_DOWN     762
#define IDR_PNG_BTN_PAUSE_PLAY_NORMAL   763
#define IDR_PNG_BTN_START_PLAY_DISABLE  764
#define IDR_PNG_BTN_START_PLAY_DOWN     765
#define IDR_PNG_BTN_EDITMEDIARIGHT_DOWN 766
#define IDR_PNG_MAINWND_BTN_ADDREDIT    767
#define IDR_PNG_MAINWND_BTN_ADDREDIT_DOWN 768
#define IDR_PNG_MAINWND_BTN_ADDREDIT_SEL 769
#define IDR_PNG_ADDREDITWND_ADDRSHOWEX_UNSEL 770
#define IDR_PNG_ADDREDITWND_ADDRSHOWEX_SEL 771
#define IDR_PNG_ADDREDITWND_ADDRSHOWEX_DOWN 772
#define IDR_PNG_BTN_DELETEITEM          773
#define IDR_PNG_BTN_DELETEITEMDOWN      774
#define IDD_DIALOG_ADDREDITSHOWOPTN     775
#define IDD_DIALOG_ADDREDITSHOWOPT      775
#define IDR_PNG_ADDREDITWND_OPT_BK      776
#define IDD_DIALOG_VIDEORECORDSHOWOPT   776
#define IDR_PNG_ADDREDITWND_BTN_LOADTOLOCAL 777
#define IDD_DIALOG_VIDEORECORDEPSHOWOPT 777
#define IDR_PNG_ADDREDITWND_BTN_LOADTOLOCAL_DISABLE 778
#define IDR_PNG_ADDREDITWND_BTN_LOADTOLOCAL_SEL 779
#define IDR_PNG_RECORDWND_ICON_PLAY     781
#define IDR_PNG_RECORDWND_ICON_RECORD   782
#define IDR_PNG_RECORDWND_ICON_RECORDEP 783
#define IDR_PNG_ADDREDITWND_ICON_NEWGROUP 785
#define IDR_PNG_ADDREDITWND_ICON_IMPORTADDRBOOK 786
#define IDR_PNG_ADDREDITWND_ICON_OFFLINE 787
#define IDR_PNG_ADDREDITWND_ICON_ONLINE 788
#define IDR_PNG_RECORDWND_OPT_BK        790
#define IDR_PNG_PROGRESS_RIGHT_HIGH     791
#define IDR_PNG_PROGRESS_MID_HIGH       792
#define IDR_PNG_PROGRESS_LEFT_HIGH      793
#define IDR_PNG_PROGRESS_RIGHT          794
#define IDR_PNG_PROGRESS_MID            795
#define IDR_PNG_PROGRESS_LEFT           796
#define IDR_PNG_BTN_NEWMEETDIS          797
#define IDR_PNG_BTN_RefreshDIS          798
#define IDR_PNG_ADDREDITWND_BTN_LOADTOLOCAL_CANCEL 799
#define IDR_PNG_ADDREDITWND_BTN_LOADTOLOCAL_DOWN 801
#define IDR_PNG_RECORDWND_EP_OPT_BK     802
#define IDR_PNG_BTN_RESUME_RECORD_NORMAL 804
#define IDR_PNG_BTN_RESUME_RECORD_DOWN  805
#define IDR_PNG_BTN_RESUME_RECORD_DISABLE 806
#define IDR_PNG_BTN_RESUME_PLAY_NORMAL  807
#define IDR_PNG_BTN_RESUME_PLAY_DOWN    808
#define IDR_PNG_BTN_RESUME_PLAY_DISABLE 809
#define IDD_DIALOG_WAITINGBOX           810
#define IDD_DIALOG_MEETDISCUSS          811
#define IDR_PNG_MEETTMPWND_BTN_ALLREMOVEDIS 812
#define IDR_PNG_MEETTMPWND_BTN_MEETDISCUSS 813
#define IDR_PNG_MEETTMPWND_BTN_MEETDISCUSSDOWN 814
#define IDR_PNG_MEETTMPWND_BTN_MEETDISCUSSSEL 815
#define IDR_PNG_MEETTMPWND_BTN_MEETCONFFORMAT 816
#define IDR_PNG_MEETTMPWND_BTN_MEETCONFFORMATDOWN 817
#define IDR_PNG_MEETTMPWND_BTN_MEETCONFFORMATSEL 818
#define IDR_PNG_MEETTMPWND_BTN_MEETSHOWFORMAT 819
#define IDR_PNG_MEETTMPWND_BTN_MEETSHOWFORMATDOWN 820
#define IDR_PNG_MEETTMPWND_BTN_MEETSHOWFORMATSEL 821
#define IDR_PNG_MEETTMPWND_BTN_MEETAUDIOFORMAT 822
#define IDR_PNG_MEETTMPWND_BTN_MEETAUDIOFORMATDOWN 823
#define IDR_PNG_MEETTMPWND_BTN_MEETAUDIOFORMATSEL 824
#define IDR_PNG_BTN_PLUSDIS             825
#define IDR_PNG_BTN_SUBDIS              826
#define IDR_ToolItem_Cancel             32768
#define IDR_ToolItem_System             32769
#define IDR_ToolItem_Set                32770
#define IDR_ToolItem_User               32771
#define IDR_ToolItem_MeetingList        32772
#define IDR_ToolItem_MeetingTemplate    32773
#define IDR_ToolItem_PublicAddr         32774
#define IDR_ToolItem_LocalAddr          32775
#define IDR_ToolItem_Logo               32776
#define ID_MenuItem_All                 32781
#define ID_MenuItem_Current             32782
#define ID_MenuItem_Order               32785
#define IDM_MenuItem_ALL                32788
#define IDM_MenuItem_Current            32789
#define IDM_MenuItem_Order              32790

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        812
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         552
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
